package com.example.myapplication.http_api


import com.example.myapplication.viewmodels.AuthViewModel
import com.example.myapplication.viewmodels.MovieDetailViewModel
import com.example.myapplication.viewmodels.MovieViewModel
import com.example.myapplication.viewmodels.ProfileViewModel
import de.jensklingenberg.ktorfit.Ktorfit
import io.ktor.client.HttpClient
import io.ktor.client.plugins.DefaultRequest
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.request.header
import io.ktor.serialization.kotlinx.json.json
import kotlinx.serialization.json.Json
import org.koin.core.module.dsl.viewModel
import org.koin.dsl.module
import kotlinx.coroutines.launch



val networkModule = module {
    // 1. Provide the Json configuration
    single {
        Json {
            ignoreUnknownKeys = true // Ignore fields sent by API that aren't in our model
            isLenient = true
            coerceInputValues = true
        }
    }

    // 2. Provide Ktor's HttpClient
    single {
        HttpClient {
            install(ContentNegotiation) {
                json(get<Json>()) // Use the Json configuration provided above
            }
        }
    }

    // 3. Provide Ktorfit
    single {
        Ktorfit.Builder()
            .baseUrl("https://rma.finlab.rs/")
            .httpClient(get<HttpClient>())
            .build()
    }

    // 4. Provide the MovieApiService generated by Ktorfit
    single {
        get<Ktorfit>().create<MovieApiService>()
    }

    single {
        get<Ktorfit>().create<AuthApiService>()
    }
}
val repositoryModule = module {
    single { MovieRepository(get()) }
    single { AuthRepository(get()) }
}

val viewModelModule = module {
    //factory { MovieViewModel(get()) }
    viewModel { MovieViewModel(get()) }
}

val detailviewModelModule = module {
    //factory { (id: String) -> MovieDetailViewModel(get(), id) }
    viewModel { (id: String) -> MovieDetailViewModel(get(), id) }
}

val authviewModelModule = module {
    viewModel { AuthViewModel(get(), get()) }
}

val profileviewModelModule = module {
    viewModel { ProfileViewModel(get(),get()) }
}


val appModules = listOf(networkModule, repositoryModule, viewModelModule, detailviewModelModule, authviewModelModule, profileviewModelModule)