package com.example.myapplication.http_api

import com.example.myapplication.viewmodels.MovieDetailViewModel
import com.example.myapplication.viewmodels.MovieViewModel
import de.jensklingenberg.ktorfit.Ktorfit
import io.ktor.client.HttpClient
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.serialization.kotlinx.json.json
import kotlinx.serialization.json.Json
import org.koin.dsl.module


val networkModule = module {
    // 1. Provide the Json configuration
    single {
        Json {
            ignoreUnknownKeys = true // Ignore fields sent by API that aren't in our model
            isLenient = true
            coerceInputValues = true
        }
    }

    // 2. Provide Ktor's HttpClient
    single {
        HttpClient {
            install(ContentNegotiation) {
                json(get<Json>()) // Use the Json configuration provided above
            }
        }
    }

    // 3. Provide Ktorfit
    single {
        Ktorfit.Builder()
            .baseUrl("https://rma.finlab.rs/")
            .httpClient(get<HttpClient>())
            .build()
    }

    // 4. Provide the MovieApiService generated by Ktorfit
    single {
        get<Ktorfit>().create<MovieApiService>()
    }
}
val repositoryModule = module {
    single { MovieRepository(get()) }
}

val viewModelModule = module {
    factory { MovieViewModel(get()) }
}

val detailviewModelModule = module {
    factory { MovieDetailViewModel(get(), "") }
}

val appModules = listOf(networkModule, repositoryModule, viewModelModule, detailviewModelModule)